name: ドキュメント改善テンプレート
description: ドキュメントの追加・修正はこちらから
labels: ["docs"]
body:
  - type: textarea
    id: task
    attributes:
      label: やるべきこと
      placeholder: 追加・修正したいドキュメントの内容を説明してください
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: 完了条件
      placeholder: このドキュメント改善が完了したと判断できる条件
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 参考資料
      placeholder: 関連するリンク
    validations:
      required: false
